name: msiparse
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - intel-openmp=2019.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - mkl=2019.4
  - numpy=1.17.3
  - openssl=1.1.1d
  - pandas=0.25.3
  - pytables=3.6.1
  - pip=19.3.1
  - pyimzml=1.2.6
  - python=3.8.0
  - python-dateutil=2.8.1
  - pytz=2019.3
  - setuptools=42.0.1
  - six=1.13.0
  - sqlite=3.30.1
  - wheel=0.33.6
  - wheezy.template=0.1.167
  - pip:
    - opencv-python==4.1.2.30